# docker-compose.mcp-postgres.yml - MCP PostgreSQL デモ用最小構成
version: '3.8'

services:
  # PostgreSQL データベース (必須)
  postgres:
    image: postgres:15-alpine
    container_name: mcp-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-data/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mcp-network

volumes:
  postgres_data:

networks:
  mcp-network:
    name: mcp-network
    external: false