# docker-compose.yml
# version: '3.8'
services:
  # === データベース系 ===
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  qdrant_data:

networks:
  default:
    name: qdrant-network